using System.Collections.Generic;
using System.Threading.Tasks;
using Project.QuizSystem;
using Project.RewardSystem;
using Project.Utils;
using UnityEngine;

namespace Project.MiniGames
{
    public class AutoGeneratedTaskGiver : TaskGiver
    {
        [SerializeField] private TaskSTO Template;
        
        protected override async Task InitTasks()
        {
            await Task.Run(() =>
            {
                Tasks = new(Reward.Goal, "");
                Tasks.OnTaskChanged += ChangeTask;

                for (int i = 0; i < Reward.Goal; i++)
                {
                    BaseTask task = Template.GetTask();
                    Tasks.AddTask(task);
                }
            });
            ChangeTask(Tasks.CurrentTask);
        }
    }
}